# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-03-12 15:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('viewer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Snapshot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[(b'INIT', b'INIT'), (b'AUTO', b'AUTO'), (b'MANUAL', b'MANUAL')], default=b'INIT', max_length=8)),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('data', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('children', models.ManyToManyField(null=True, related_name='_snapshot_children_+', to='viewer.Snapshot')),
            ],
            options={
                'permissions': (('view_project', 'View project'),),
            },
        ),
        migrations.RemoveField(
            model_name='project',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='target',
            name='project_id',
        ),
        migrations.AddField(
            model_name='project',
            name='author',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.CharField(default='My project description', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='tags',
            field=models.TextField(default=[]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='target',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='viewer.Target'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='init_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AddField(
            model_name='snapshot',
            name='projectID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viewer.Project'),
        ),
    ]
