# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-03-12 15:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0002_auto_20200312_1506'),
    ]

    operations = [
        migrations.RenameField(
            model_name='snapshot',
            old_name='projectID',
            new_name='project',
        ),
    ]
