# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-03-12 15:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0003_auto_20200312_1510'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compound',
            name='project_id',
        ),
    ]
